### ISSUE TITLE
Crash when loading into world

### ISSUE THREAD

**Issue by RobertHoueland** [A5b84/status-effect-bars#1]
I have quite a few other mods installed, so it might be a conflict.

Crash report:

```---- Minecraft Crash Report ----
Time: 5/2/22, 6:20 PM
Description: Unexpected error

org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_329::method_1765(Lnet/minecraft/class_4587;)V has incompatible changes at opcode 261 in callback status-effect-bars.mixins.json:InGameHudMixin->@Inject::onRenderStatusEffectOverlay(Lnet/minecraft/class_4587;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Ljava/util/Collection;IILnet/minecraft/class_4074;Ljava/util/List;Ljava/util/Iterator;Lnet/minecraft/class_1293;Lnet/minecraft/class_1291;II)V from mod status-effect-bars.
 Expected: [Ljava/util/Collection;, I, I, Lnet/minecraft/class_4074;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1293;, Lnet/minecraft/class_1291;, I, I]
    Found: [Ljava/util/Collection;, Lnet/minecraft/class_437;, I, I, Lnet/minecraft/class_4074;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1293;, Lnet/minecraft/class_1291;, Lnet/minecraftforge/client/EffectRenderer;]
Available: [Ljava/util/Collection;, Lnet/minecraft/class_437;, I, I, Lnet/minecraft/class_4074;, Ljava/util/List;, Ljava/util/Iterator;, Lnet/minecraft/class_1293;, Lnet/minecraft/class_1291;, Lnet/minecraftforge/client/EffectRenderer;, I, I, F, I]
	at net.minecraft.class_329.handler$zpi000$onRenderStatusEffectOverlay$missing(class_329.java)
	at net.minecraft.class_329.method_1765(class_329.java:624)
	at net.minecraft.class_329.method_1753(class_329.java:311)
	at net.minecraft.class_757.method_3192(class_757.java:1219)
	at net.minecraft.class_310.method_1523(class_310.java:1122)
	at net.minecraft.class_310.method_1514(class_310.java:737)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_329.handler$zpi000$onRenderStatusEffectOverlay$missing(class_329.java)
	at net.minecraft.class_329.method_1765(class_329.java:624)
	at net.minecraft.class_329.method_1753(class_329.java:311)

-- Affected level --
Details:
	All players: 1 total; [class_746['robdog777'/109, l='ClientLevel', x=18.48, y=74.00, z=8.98]]
	Chunk stats: 961, 600
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,74,0), Section: (at 0,10,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 9619 game time, 9619 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:516)
	at net.minecraft.class_310.method_1587(class_310.java:2376)
	at net.minecraft.class_310.method_1514(class_310.java:761)
	at net.minecraft.client.main.Main.main(Main.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, VanillaTweaks_r815094.zip, colored-axolotl-buckets-e3460.zip, Better_Dogs_V1.17.zip, ClearVision1.4.zip, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 612553528 bytes (584 MiB) / 1409286144 bytes (1344 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.70
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1060 6GB
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c03
	Graphics card #0 versionInfo: DriverVersion=30.0.15.1259
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29139.28
	Virtual memory used (MB): 21550.78
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 506.21
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		appleskin: AppleSkin 2.4.0+mc1.18.2
		architectury: Architectury 4.2.50
		autofish: Autofish 0.9.4
		blue_endless_jankson: jankson 1.2.1
		boostedbrightness: Boosted Brightness 2.1.1
		chat_heads: Chat Heads 0.6.0
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		dark-loading-screen: Dark Loading Screen 1.6.11
		dynamicfps: Dynamic FPS 2.1.0
		enchantmentsplus: Enchantments Plus 1.0.9+1.18.2
		entityculling: EntityCulling-Fabric 1.5.1
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		fastchest: FastChest 1.2+1.18
		ferritecore: FerriteCore 4.2.1
		held-item-info: Held Item Info 1.2.0
		horsestatsvanilla: Horse Stats Vanilla 4.1.10
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		krypton: Krypton 0.1.9
		lazydfu: LazyDFU 0.1.2
		libgui: LibGui 5.0.0-beta.2+1.18-rc1
		libninepatch: LibNinePatch 1.1.0
		lightoverlay: Light Overlay 6.0.5
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.2.1
		optifabric: OptiFabric 1.13.0
		roughlyenoughitems: Roughly Enough Items 8.1.457
		smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
		starlight: Starlight 1.0.2+fabric.89b8d9f
		status-effect-bars: Status Effect Bars 1.0.0
		xaerominimap: Xaero's Minimap 22.6.1
	Launched Version: fabric-loader-0.13.3-1.18.2
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 3.2.0 NVIDIA 512.59, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, file/VanillaTweaks_r815094.zip, file/colored-axolotl-buckets-e3460.zip, file/Better_Dogs_V1.17.zip, file/ClearVision1.4.zip
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['robdog777'/109, l='ServerLevel[New World]', x=18.48, y=74.00, z=8.98]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	OptiFine Version: OptiFine_1.18.2_HD_U_H7
	OptiFine Build: 20220410-185216
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 512.59
	OpenGlRenderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.18.2
	OptiFine jar version: OptiFine_1.18.2_HD_U_H7
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:/Users/angry/AppData/Roaming/.minecraft/.optifine/OptiFine_1.18.2_HD_U_H7/Optifine-mapped.jar
	OptiFabric error: <None>```

**Comment by A5b84** [comment]
I haven't had time to look into it yet but I think it could be caused by Optifabric (see [this](https://lambdaurora.dev/optifine_alternatives/) if it's indeed the cause and if you're looking for alternatives to Optifine)

**Comment by RobertHoueland** [comment]
Yep, I just tried removing optifine and optifabric and I was able to load into a world just fine
